package sybyla.mapred.workflow;

/**
 * Copyright SocialInSoma, 2013
 * User: kiko
 * Date: 10/23/13
 * Time: 12:43 PM
 */
public enum WorkflowCounters {

    NUMBER_OF_DOCUMENTS,
    NUMBER_OF_FEATURES,
    NUMBER_OF_FEATURES_EXCLUDED_WITH_LOW_SIGNIFICANCE,
    NUMBER_OF_FEATURES_KEPT_WITH_HIGH_SIGNIFICANCE,
    NUMBER_OF_TRAINING_EXAMPLES,
    NUMBER_OF_TRAINING_ITERATIONS,
    NUMBER_OF_CATEGORY_MODELS,
    NUMBER_OF_CATEGORY_MODEL_TERMS,
    NUMBER_OF_AUTO_PRUNED_TERMS,
    NUMBER_OF_TRAINING_EXAMPLES_FIRST_PASS,
    NUMBER_OF_AUTO_PRUNING_EVENTS,
    HIGH_WATER_MEMORY_USAGE,
    LOW_WATER_FREE_MEMORY,
    HIGH_WATER_TOTAL_MEMORY,
    WINNOW_TERMS_MB,
    WINNOW_EXCLUDED_TERMS_MB,
    NUMBER_OF_TRAINING_EXAMPLES_POST_AUTO_PRUNING;
}
